In [1]:
import torch as th 

# Aim 
* Understnad how to perform mathematical operations on a torch.tesnor 

# Introduction 

Tensors support following operations 
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Transpose 
* Aggregation : min, max, mean, sum and etc 
* Matrix multiplication

# Basic Operations 

In [10]:
vector_a = th.tensor([1, 2, 3, 4])
vector_b = th.tensor([5, 6, 7, 8])

# Add the two vectors
vector_sum = vector_a + vector_b
print(vector_sum)

# Subtract the two vectors
vector_diff = vector_a - vector_b
print(vector_diff)

# Element-wise multiplication
element_wise_product = vector_a * vector_b
print(element_wise_product)

# Element-wise division
element_wise_division = vector_a / vector_b
print(element_wise_division)

# Transpose of a tensor
MATRIX_3_2 = th.tensor([[1, 2], [3, 4], [5, 6]])
MATRIX_3_2_T = MATRIX_3_2.t()
print(f'MATRIX_3_2: {MATRIX_3_2}')
print(f'MATRIX_3_2_T: {MATRIX_3_2_T}')
print(f'MATRIX_3_2_T shape: {MATRIX_3_2_T.shape}')
print(f'MATRIX_3_2 size: {MATRIX_3_2.shape}')


tensor([ 6,  8, 10, 12])
tensor([-4, -4, -4, -4])
tensor([ 5, 12, 21, 32])
tensor([0.2000, 0.3333, 0.4286, 0.5000])
MATRIX_3_2: tensor([[1, 2],
        [3, 4],
        [5, 6]])
MATRIX_3_2_T: tensor([[1, 3, 5],
        [2, 4, 6]])
MATRIX_3_2_T shape: torch.Size([2, 3])
MATRIX_3_2 size: torch.Size([3, 2])


# Tensor Aggregation 

In [21]:
vector = th.rand(10, dtype=th.float32)

print(vector)

# Min 
print(f'Min of vector: {vector.min()}')
print(f'Min position of vector: {vector.argmin()}')

# Max
print(f'Max of vector: {vector.max()}')
print(f'Max position of vector: {vector.argmax()}')

# Sum
print(f'Sum of vector: {vector.sum()}')

# Mean
print(f'Mean of vector: {vector.mean()}')

tensor([0.5775, 0.4105, 0.2812, 0.5376, 0.8034, 0.9054, 0.9132, 0.3178, 0.2643,
        0.4841])
Min of vector: 0.26427483558654785
Min position of vector: 8
Max of vector: 0.9132288694381714
Max position of vector: 6
Sum of vector: 5.494887351989746
Mean of vector: 0.5494887232780457


# Matrix multiplcation 

Following are the dimential related matix multiplcation rules

1. The innner dimentions should mathc 
    * (3, 2) @ (3, 2) won't work
    * (2, 3) @ (3, 2) will work
    * (3, 2) @ (2, 3) will work
2. The resulting matrix will have the shape of outer outer dimention 
    * (3, 2) @ (2, 3) will result in a matrix of (3, 3) shape
    * (2, 3) @ (3, 2) will result in a matrix of (2, 2) shape

`@` or `torch.matmul()` / `torch.mm()` are the matrix multipication operators

In [5]:
MATRIX_A = th.tensor([[1, 2, 3], [4, 5, 6]])
MATRIX_B = th.tensor([[7, 8], [9, 10], [11, 12]])
print(f'MATRIX_A: {MATRIX_A}')
print(f'MATRIX_B: {MATRIX_B}')
print(f'Shape of MATRIX_A and MATRIX_B: {MATRIX_A.shape}, {MATRIX_B.shape}') 
print(f'MATRIX_A * MATRIX_B: {th.matmul(MATRIX_A, MATRIX_B)}')

MATRIX_A: tensor([[1, 2, 3],
        [4, 5, 6]])
MATRIX_B: tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])
Shape of MATRIX_A and MATRIX_B: torch.Size([2, 3]), torch.Size([3, 2])
MATRIX_A * MATRIX_B: tensor([[ 58,  64],
        [139, 154]])


In [8]:
# Matrix multiplication with incompatible shapes
A_3_2 = th.tensor([[1, 2], [3, 4], [5, 6]])
B_3_3 = th.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

try:
    A_3_2 @ B_3_3
except Exception as e:
    print(f'Error: {e}')


Error: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x3)
